interface Window {
  $dataActors: DB.Actor[];
  $dataClasses: DB.Class[];
  $dataSkills: DB.Skill[];
  $dataItems: DB.Item[];
  $dataWeapons: DB.Weapon[];
  $dataArmors: DB.Armor[];
  $dataEnemies: DB.Enemy[];
  $dataTroops: DB.Troop[];
  $dataStates: DB.State[];
  $dataAnimations: DB.Animation[];
  $dataTilesets: DB.Tileset[];
  $dataCommonEvents: DB.CommonEvent[];
  $dataSystem: DB.System;
  $dataMapInfos: DB.MapInfo[];
  $dataMap: DB.Map;
  $gameTemp: Game_Temp;
  $gameSystem: Game_System;
  $gameScreen: Game_Screen;
  $gameTimer: Game_Timer;
  $gameMessage: Game_Message;
  $gameSwitches: Game_Switches;
  $gameVariables: Game_Variables;
  $gameSelfSwitches: Game_SelfSwitches;
  $gameActors: Game_Actors;
  $gameParty: Game_Party;
  $gameTroop: Game_Troop;
  $gameMap: Game_Map;
  $gamePlayer: Game_Player;
  $testEvent: DB.List[];
}

declare var $dataActors: DB.Actor[];
declare var $dataClasses: DB.Class[];
declare var $dataSkills: DB.Skill[];
declare var $dataItems: DB.Item[];
declare var $dataWeapons: DB.Weapon[];
declare var $dataArmors: DB.Armor[];
declare var $dataEnemies: DB.Enemy[];
declare var $dataTroops: DB.Troop[];
declare var $dataStates: DB.State[];
declare var $dataAnimations: DB.Animation[];
declare var $dataTilesets: DB.Tileset[];
declare var $dataCommonEvents: DB.CommonEvent[];
declare var $dataSystem: DB.System;
declare var $dataMapInfos: DB.MapInfo[];
declare var $dataMap: DB.Map;
declare var $gameTemp: Game_Temp;
declare var $gameSystem: Game_System;
declare var $gameScreen: Game_Screen;
declare var $gameTimer: Game_Timer;
declare var $gameMessage: Game_Message;
declare var $gameSwitches: Game_Switches;
declare var $gameVariables: Game_Variables;
declare var $gameSelfSwitches: Game_SelfSwitches;
declare var $gameActors: Game_Actors;
declare var $gameParty: Game_Party;
declare var $gameTroop: Game_Troop;
declare var $gameMap: Game_Map;
declare var $gamePlayer: Game_Player;
declare var $testEvent: DB.List[];
